services:
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
  event-bus:
    container_name: go-event-bus
    build:
      context: ./events
    depends_on:
      - cache
    ports:
      - "8080:8080"
